#!/bin/bash

# check if we are on openmamba
if [ ! -f /etc/openmamba-release ]; then
    echo "This script is only for openmamba"
    exit
fi


# check if we are root
if [ "$EUID" -eq 0 ]
  then echo "Please run as normal user"
  exit
fi

# Controlla se il primo argomento è vuoto
if [ -z "$1" ]; then
  VERSION=10.0.54
else
  VERSION=$1  
fi


sudo wget https://github.com/pieroproietti/penguins-eggs/archive/refs/tags/v$VERSION.tar.gz -O /usr/src/RPM/SOURCES/penguins-eggs-$VERSION.tar.gz

