#!/bin/bash

# check if we are on rocky/almalinux
if [ ! -f /etc/rocky-release ]; then
    if [ ! -f /etc/almalinux-release ]; then
        echo "This script is intended for rockylinux or almalinux!"
        exit 1
    fi
fi

# check if we are root
if [ "$EUID" -eq 0 ]
  then echo "Please run as normal user"
  exit
fi

# Controlla se il primo argomento è vuoto
if [ -z "$1" ]; then
  VERSION=10.0.54
else
  VERSION=$1  
fi

wget https://github.com/pieroproietti/penguins-eggs/archive/refs/tags/v$VERSION.tar.gz -O ~/rpmbuild/SOURCES/penguins-eggs-$VERSION.tar.gz

